// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm0S1TTbTI7x4CaITOHtLu7KNWZKimJPc',
    appId: '1:1063937132239:web:6f2ba3ba47d35a69c7d9ba',
    messagingSenderId: '1063937132239',
    projectId: 'sante-focus-29c2f',
    authDomain: 'sante-focus-29c2f.firebaseapp.com',
    storageBucket: 'sante-focus-29c2f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvAhLP_BpYNSRwxm3O3W_vP7gzKoXc5ew',
    appId: '1:1063937132239:android:e375a2c990592dc7c7d9ba',
    messagingSenderId: '1063937132239',
    projectId: 'sante-focus-29c2f',
    storageBucket: 'sante-focus-29c2f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVRMgBYVUZVZNiQFy3NNYFN8Aj0WsaB5U',
    appId: '1:1063937132239:ios:f4c18ba9f4058b5dc7d9ba',
    messagingSenderId: '1063937132239',
    projectId: 'sante-focus-29c2f',
    storageBucket: 'sante-focus-29c2f.firebasestorage.app',
    iosBundleId: 'com.example.santefocus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVRMgBYVUZVZNiQFy3NNYFN8Aj0WsaB5U',
    appId: '1:1063937132239:ios:f4c18ba9f4058b5dc7d9ba',
    messagingSenderId: '1063937132239',
    projectId: 'sante-focus-29c2f',
    storageBucket: 'sante-focus-29c2f.firebasestorage.app',
    iosBundleId: 'com.example.santefocus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAm0S1TTbTI7x4CaITOHtLu7KNWZKimJPc',
    appId: '1:1063937132239:web:a7a268c4766dc9bdc7d9ba',
    messagingSenderId: '1063937132239',
    projectId: 'sante-focus-29c2f',
    authDomain: 'sante-focus-29c2f.firebaseapp.com',
    storageBucket: 'sante-focus-29c2f.firebasestorage.app',
  );
}
